import type { PartyData, PromiseData, RegionId, RegionInfo } from './types';

export const REGIONS: Record<RegionId, RegionInfo> = {
  norrland: {
    id: 'norrland',
    name: 'Norrland',
    fullName: 'Norra Sverige & inlandet',
    description: 'Viktiga frågor: Industri & grön omställning, vägnät, energipriser, avstånd och lokal sjukvård.',
    electorateWeight: 0.125,
    mandates: 44,
    primaryCategories: ['infrastruktur', 'klimat-miljö', 'välfärd', 'försvar'],
    x: 62,
    y: 28,
  },
  svealand: {
    id: 'svealand',
    name: 'Mellansverige',
    fullName: 'Svealand & Bergslagen (exkl. Sthlm)',
    description: 'Viktiga frågor: Skola, industri, arbetsmarknad och regional sammanhållning.',
    electorateWeight: 0.165,
    mandates: 58,
    primaryCategories: ['utbildning', 'skatter', 'välfärd', 'infrastruktur'],
    x: 52,
    y: 60,
  },
  stockholm: {
    id: 'stockholm',
    name: 'Stockholm',
    fullName: 'Stockholmsregionen & Mälardalen',
    description: 'Viktiga frågor: Bostadsbrist, skatter, rättsväsende och kollektivtrafik.',
    electorateWeight: 0.220,
    mandates: 77,
    primaryCategories: ['skatter', 'rättsväsende', 'klimat-miljö', 'utbildning'],
    x: 74,
    y: 66,
  },
  vastsverige: {
    id: 'vastsverige',
    name: 'Västsverige',
    fullName: 'Västra Götaland, Halland & Värmland',
    description: 'Viktiga frågor: Hamnar, exportindustri, infrastruktur, sjukvård och näringsliv.',
    electorateWeight: 0.245,
    mandates: 86,
    primaryCategories: ['infrastruktur', 'skatter', 'välfärd', 'rättsväsende'],
    x: 35,
    y: 75,
  },
  sydsverige: {
    id: 'sydsverige',
    name: 'Sydsverige',
    fullName: 'Skåne, Blekinge, Småland & Öarna',
    description: 'Viktiga frågor: Trygghet, elpriser i elområde 4, jordbruk och gränsöverskridande tågpendling.',
    electorateWeight: 0.245,
    mandates: 84,
    primaryCategories: ['rättsväsende', 'klimat-miljö', 'skatter', 'välfärd'],
    x: 48,
    y: 89,
  },
};

export const DEFAULT_PARTIES: PartyData[] = [
  { code: 's', name: 'Socialdemokraterna', color: '#EE2020', color_text: '#EE2020', block: 'rödgrönt', mandate_2022: 107 },
  { code: 'm', name: 'Moderaterna', color: '#1B5CB3', color_text: '#1B5CB3', block: 'borgerligt', mandate_2022: 68 },
  { code: 'sd', name: 'Sverigedemokraterna', color: '#DDDDDD', color_text: '#4B4B4B', block: 'borgerligt', mandate_2022: 73 },
  { code: 'c', name: 'Centerpartiet', color: '#00939D', color_text: '#006E76', block: 'borgerligt', mandate_2022: 24 },
  { code: 'v', name: 'Vänsterpartiet', color: '#DA291C', color_text: '#DA291C', block: 'rödgrönt', mandate_2022: 24 },
  { code: 'kd', name: 'Kristdemokraterna', color: '#2B4A7E', color_text: '#2B4A7E', block: 'borgerligt', mandate_2022: 19 },
  { code: 'l', name: 'Liberalerna', color: '#006AB3', color_text: '#006AB3', block: 'borgerligt', mandate_2022: 16 },
  { code: 'mp', name: 'Miljöpartiet', color: '#53A524', color_text: '#3D7A1A', block: 'rödgrönt', mandate_2022: 18 },
];

export const MOCK_PROMISES: PromiseData[] = [
  // Socialdemokraterna
  {
    id: 'p-s-01',
    title: 'Höjt barn- och studiebidrag samt plånboksskydd för barnfamiljer',
    slug: 'hojt-barn-och-studiebidrag-samt-planboksskydd',
    parties: ['s'],
    category: 'välfärd',
    status: 'aktiv',
    cost: {
      msek_base: 4800,
      type: 'utgift',
      period: 'per_ar',
      calculation: 'Höjning av barnbidrag med 200 kr/mån samt indexerat studiebidrag.',
    },
    quote: 'Vi ska ge tillbaka det du förlorat med ett plånbokslöfte för barnfamiljer och unga.',
    source: { url: 'https://utlovat.se/lofte/p-s-01', domain: 'utlovat.se' },
  },
  {
    id: 'p-s-02',
    title: 'Statligt investeringsprogram för järnvägsunderhåll och stambanor',
    slug: 'statligt-investeringsprogram-jarnvagsunderhall',
    parties: ['s'],
    category: 'infrastruktur',
    status: 'aktiv',
    cost: {
      msek_base: 12000,
      type: 'investering',
      period: 'engang',
      calculation: 'Prioritering av dubbelspår och kapacitetshöjningar i godstransportstråk.',
    },
    quote: 'Tågen måste gå i tid. Vi investerar i järnvägsunderhåll i hela landet.',
    source: { url: 'https://utlovat.se/lofte/p-s-02', domain: 'utlovat.se' },
  },
  {
    id: 'p-s-03',
    title: 'Tandvårdsreform: Tandvård ska kosta som vanlig sjukvård',
    slug: 'tandvardsreform-som-vanlig-sjukvard',
    parties: ['s'],
    category: 'välfärd',
    status: 'aktiv',
    cost: {
      msek_base: 7500,
      type: 'utgift',
      period: 'per_ar',
      calculation: 'Tiohundrakronors-tak i högkostnadsskydd för tandvård.',
    },
    quote: 'Tänderna är en del av kroppen. Tandvården ska ingå i det generella högkostnadsskyddet.',
    source: { url: 'https://utlovat.se/lofte/p-s-03', domain: 'utlovat.se' },
  },
  {
    id: 'p-s-04',
    title: 'Fler anställda i förskolan och mindre barngrupper',
    slug: 'fler-anstallda-forskolan-mindre-barngrupper',
    parties: ['s'],
    category: 'utbildning',
    status: 'aktiv',
    cost: {
      msek_base: 3200,
      type: 'utgift',
      period: 'per_ar',
      calculation: 'Riktade statsbidrag för att minska barngruppernas storlek.',
    },
    quote: 'Tidiga insatser och trygga barngrupper i förskolan lägger grunden för hela skolgången.',
    source: { url: 'https://utlovat.se/lofte/p-s-04', domain: 'utlovat.se' },
  },

  // Moderaterna
  {
    id: 'p-m-01',
    title: 'Sänkt skatt på arbete genom förstärkt jobbskatteavdrag',
    slug: 'sankt-skatt-pa-arbete-jobbskatteavdrag',
    parties: ['m'],
    category: 'skatter',
    status: 'aktiv',
    cost: {
      msek_base: 11000,
      type: 'skattesankning',
      period: 'per_ar',
      calculation: 'Sänkt inkomstskatt för hel- och deltidsarbetande med tyngdpunkt på låg- och medelinkomster.',
    },
    quote: 'Det ska alltid löna sig bättre att arbeta än att leva på bidrag.',
    source: { url: 'https://utlovat.se/lofte/p-m-01', domain: 'utlovat.se' },
  },
  {
    id: 'p-m-02',
    title: 'Utbyggnad av fossilfri kärnkraft och snabbspår för nya reaktorer',
    slug: 'utbyggnad-fossilfri-karnkraft',
    parties: ['m'],
    category: 'klimat-miljö',
    status: 'aktiv',
    cost: {
      msek_base: 8000,
      type: 'kreditgaranti',
      period: 'engang',
      calculation: 'Statliga kreditgarantier och förenklat tillståndsförfarande för SMR.',
    },
    quote: 'Sverige behöver ren och planerbar el dygnet runt, året runt för industrins omställning.',
    source: { url: 'https://utlovat.se/lofte/p-m-02', domain: 'utlovat.se' },
  },
  {
    id: 'p-m-03',
    title: 'Skärpta straff för gängkriminalitet och utökade visitationszoner',
    slug: 'skarpta-straff-gangkriminalitet-visitationszoner',
    parties: ['m'],
    category: 'rättsväsende',
    status: 'aktiv',
    cost: {
      msek_base: 3500,
      type: 'utgift',
      period: 'per_ar',
      calculation: 'Utbyggd kriminalvård och kapacitetsökning inom polisens utredningsresurser.',
    },
    quote: 'Den som begår grova brott ska sitta bakom lås och bom för att skydda hederliga medborgare.',
    source: { url: 'https://utlovat.se/lofte/p-m-03', domain: 'utlovat.se' },
  },
  {
    id: 'p-m-04',
    title: 'Borttaget amorteringskrav och reformerade bolåneregler för unga',
    slug: 'borttaget-amorteringskrav-unga',
    parties: ['m'],
    category: 'skatter',
    status: 'aktiv',
    cost: {
      msek_base: 0,
      type: 'regelreform',
      period: 'engang',
      calculation: 'Regeländring hos Finansinspektionen utan direkt budgetpåverkan.',
    },
    quote: 'Trösklarna in på bostadsmarknaden måste sänkas för förstagångsköpare.',
    source: { url: 'https://utlovat.se/lofte/p-m-04', domain: 'utlovat.se' },
  },

  // Sverigedemokraterna
  {
    id: 'p-sd-01',
    title: 'Sänkt reduktionsplikt och kraftigt sänkt drivmedelsskatt vid pump',
    slug: 'sankt-reduktionsplikt-och-drivmedelsskatt',
    parties: ['sd'],
    category: 'skatter',
    status: 'aktiv',
    cost: {
      msek_base: 6500,
      type: 'skattesankning',
      period: 'per_ar',
      calculation: 'Sänkning av energiskatt på bensin och diesel.',
    },
    quote: 'Sverigepriser på bränsle så att folk och företag i hela landet har råd att köra.',
    source: { url: 'https://utlovat.se/lofte/p-sd-01', domain: 'utlovat.se' },
  },
  {
    id: 'p-sd-02',
    title: 'Skärpt återvandringsbidrag och stram migrationspolitik',
    slug: 'skarpt-atervandringsbidrag-migrationspolitik',
    parties: ['sd'],
    category: 'migration',
    status: 'aktiv',
    cost: {
      msek_base: 2200,
      type: 'utgift',
      period: 'per_ar',
      calculation: 'Höjda incitament för frivillig återvandring samt förstärkt gränskontroll.',
    },
    quote: 'En ansvarsfull migrationspolitik och ökade resurser för frivillig återvandring.',
    source: { url: 'https://utlovat.se/lofte/p-sd-02', domain: 'utlovat.se' },
  },
  {
    id: 'p-sd-03',
    title: 'Obligatorisk utvisning vid grova brott för utländska medborgare',
    slug: 'obligatorisk-utvisning-grova-brott',
    parties: ['sd'],
    category: 'rättsväsende',
    status: 'aktiv',
    cost: {
      msek_base: 1400,
      type: 'utgift',
      period: 'per_ar',
      calculation: 'Lagändring och fler förvarsplatser hos Migrationsverket och Kriminalvården.',
    },
    quote: 'Begår man brott i Sverige som utländsk medborgare ska man avtjäna straff och utvisas.',
    source: { url: 'https://utlovat.se/lofte/p-sd-03', domain: 'utlovat.se' },
  },
  {
    id: 'p-sd-04',
    title: 'Höjt grundavdrag för pensionärer och slopad pensionärsskatt',
    slug: 'hojt-grundavdrag-slopad-pensionarsskatt',
    parties: ['sd'],
    category: 'välfärd',
    status: 'aktiv',
    cost: {
      msek_base: 4100,
      type: 'skattesankning',
      period: 'per_ar',
      calculation: 'Förstärkt grundavdrag för personer över 66 år.',
    },
    quote: 'De som byggt upp vårt land ska ha en trygg och rättvis pension att leva på.',
    source: { url: 'https://utlovat.se/lofte/p-sd-04', domain: 'utlovat.se' },
  },

  // Centerpartiet
  {
    id: 'p-c-01',
    title: 'Grön skatteväxling: Sänk skatt på jobb och företag, beskatta miljöutsläpp',
    slug: 'gron-skattevaxling-sank-skatt-pa-jobb',
    parties: ['c'],
    category: 'skatter',
    status: 'aktiv',
    cost: {
      msek_base: 5200,
      type: 'skattevaxling',
      period: 'per_ar',
      calculation: 'Budgetneutral växling mellan sänkta arbetsgivaravgifter och punktskatter på föroreningar.',
    },
    quote: 'Det ska vara billigt att göra rätt och dyrt att smutsa ner.',
    source: { url: 'https://utlovat.se/lofte/p-c-01', domain: 'utlovat.se' },
  },
  {
    id: 'p-c-02',
    title: 'Slopade arbetsgivaravgifter för ungas första jobb och småföretag',
    slug: 'slopade-arbetsgivaravgifter-ungas-forsta-jobb',
    parties: ['c'],
    category: 'skatter',
    status: 'aktiv',
    cost: {
      msek_base: 3800,
      type: 'skattesankning',
      period: 'per_ar',
      calculation: 'Nedsatta socialavgifter för första anställd och unga under 23 år.',
    },
    quote: 'Fyra av fem nya jobb skapas i småföretag. Vi sänker kostnaden att anställa.',
    source: { url: 'https://utlovat.se/lofte/p-c-02', domain: 'utlovat.se' },
  },
  {
    id: 'p-c-03',
    title: 'Garanterad bredbandsutbyggnad och mobiluppkoppling i hela landet',
    slug: 'garanterad-bredbandsutbyggnad-hela-landet',
    parties: ['c'],
    category: 'infrastruktur',
    status: 'aktiv',
    cost: {
      msek_base: 2500,
      type: 'investering',
      period: 'per_ar',
      calculation: 'Statligt bredbandsstöd till glesbygd och robust mobilinfrastruktur.',
    },
    quote: 'Hela Sverige ska leva och ha samma digitala möjligheter oavsett postadress.',
    source: { url: 'https://utlovat.se/lofte/p-c-03', domain: 'utlovat.se' },
  },
  {
    id: 'p-c-04',
    title: 'Stärk äganderätten i skogen och förenkla naturvårdsavtal',
    slug: 'stark-aganderatten-i-skogen',
    parties: ['c'],
    category: 'klimat-miljö',
    status: 'aktiv',
    cost: {
      msek_base: 1800,
      type: 'utgift',
      period: 'per_ar',
      calculation: 'Ersättning till markägare och frivilligt skydd av värdefull natur.',
    },
    quote: 'Familjeskogsbruket är ryggraden i svensk bioekonomi. Äganderätten ska respekteras.',
    source: { url: 'https://utlovat.se/lofte/p-c-04', domain: 'utlovat.se' },
  },

  // Vänsterpartiet
  {
    id: 'p-v-01',
    title: 'Förbjud vinstuttag i skola och omsorg – alla skattepengar till verksamheten',
    slug: 'forbjud-vinstuttag-skola-omsorg',
    parties: ['v'],
    category: 'utbildning',
    status: 'aktiv',
    cost: {
      msek_base: 0,
      type: 'regelreform',
      period: 'engang',
      calculation: 'Lagstiftning om non-profit för skattefinansierad välfärd.',
    },
    quote: 'Välfärden är inte till salu. Våra gemensamma skattepengar ska gå till elever och patienter.',
    source: { url: 'https://utlovat.se/lofte/p-v-01', domain: 'utlovat.se' },
  },
  {
    id: 'p-v-02',
    title: 'Sverigebiljett för kollektivtrafik: Res i hela landet för fast maxpris',
    slug: 'sverigebiljett-kollektivtrafik-fast-pris',
    parties: ['v'],
    category: 'infrastruktur',
    status: 'aktiv',
    cost: {
      msek_base: 6000,
      type: 'utgift',
      period: 'per_ar',
      calculation: 'Statlig medfinansiering till regionerna för 450 kr/månad regionalt och 750 kr nationellt.',
    },
    quote: 'Gör det enkelt och billigt att välja tåg och buss framför bilen.',
    source: { url: 'https://utlovat.se/lofte/p-v-02', domain: 'utlovat.se' },
  },
  {
    id: 'p-v-03',
    title: 'Sänkt arbetstid mot 6 timmars arbetsdag i välfärdssektorn',
    slug: 'sankt-arbetstid-valfard',
    parties: ['v'],
    category: 'välfärd',
    status: 'aktiv',
    cost: {
      msek_base: 9000,
      type: 'utgift',
      period: 'per_ar',
      calculation: 'Pilotprojekt och delfinansiering av arbetstidsförkortning inom tung vård och omsorg.',
    },
    quote: 'Fler ska orka arbeta ett helt yrkesliv utan att slita ut sig.',
    source: { url: 'https://utlovat.se/lofte/p-v-03', domain: 'utlovat.se' },
  },
  {
    id: 'p-v-04',
    title: 'Progressiv förmögenhetsskatt och miljonärsskatt på extrema tillgångar',
    slug: 'formogenhetsskatt-miljonarsskatt',
    parties: ['v'],
    category: 'skatter',
    status: 'aktiv',
    cost: {
      msek_base: -15000, // Inkomstförstärkning
      type: 'inkomst',
      period: 'per_ar',
      calculation: 'Skatt på förmögenheter över 20 miljoner kronor.',
    },
    quote: 'De rikaste måste bidra mer till skola, vård och omsorg.',
    source: { url: 'https://utlovat.se/lofte/p-v-04', domain: 'utlovat.se' },
  },

  // Kristdemokraterna
  {
    id: 'p-kd-01',
    title: 'Statligt huvudansvar för sjukvården och slopade regiongränser',
    slug: 'statligt-huvudansvar-sjukvarden',
    parties: ['kd'],
    category: 'välfärd',
    status: 'aktiv',
    cost: {
      msek_base: 4500,
      type: 'strukturreform',
      period: 'per_ar',
      calculation: 'Central samordning och nationell vårdplatskapacitet.',
    },
    quote: 'Sjukvården ska vara jämlik och tillgänglig i hela landet, inte bero på vilken region du bor i.',
    source: { url: 'https://utlovat.se/lofte/p-kd-01', domain: 'utlovat.se' },
  },
  {
    id: 'p-kd-02',
    title: 'Stärkt vårdnadsbidrag och valfrihet för barnfamiljer',
    slug: 'starkt-vardnadsbidrag-valfrihet-familjer',
    parties: ['kd'],
    category: 'välfärd',
    status: 'aktiv',
    cost: {
      msek_base: 2800,
      type: 'utgift',
      period: 'per_ar',
      calculation: 'Ökad flexibilitet i föräldraförsäkringen och kommunala vårdnadsbidrag.',
    },
    quote: 'Familjen ska själv få bestämma hur man vill fördela tid med sina barn.',
    source: { url: 'https://utlovat.se/lofte/p-kd-02', domain: 'utlovat.se' },
  },
  {
    id: 'p-kd-03',
    title: 'Äldreboendegaranti: Rätt till plats när man fyllt 85 år',
    slug: 'aldreboendegaranti-ratt-till-plats',
    parties: ['kd'],
    category: 'välfärd',
    status: 'aktiv',
    cost: {
      msek_base: 3600,
      type: 'utgift',
      period: 'per_ar',
      calculation: 'Investeringsstöd för trygghetsbostäder och äldreboenden.',
    },
    quote: 'Våra äldre ska garanteras trygghet och gemenskap utan att behöva strida mot biståndsbedömare.',
    source: { url: 'https://utlovat.se/lofte/p-kd-03', domain: 'utlovat.se' },
  },
  {
    id: 'p-kd-04',
    title: 'Fler synliga poliser i lokalsamhället och stärkt grannsamverkan',
    slug: 'fler-synliga-poliser-lokalsamhallet',
    parties: ['kd'],
    category: 'rättsväsende',
    status: 'aktiv',
    cost: {
      msek_base: 2900,
      type: 'utgift',
      period: 'per_ar',
      calculation: 'Resursförstärkning till lokalpolisområden och trygghetsinsatser.',
    },
    quote: 'Polisnärvaro i varje kommun skapar trygghet och förebygger brott.',
    source: { url: 'https://utlovat.se/lofte/p-kd-04', domain: 'utlovat.se' },
  },

  // Liberalerna
  {
    id: 'p-l-01',
    title: 'Återförstatliga skolan och inför nationell kunskapsskola med ordning och reda',
    slug: 'aterforstatliga-skolan-kunskapsskola',
    parties: ['l'],
    category: 'utbildning',
    status: 'aktiv',
    cost: {
      msek_base: 5500,
      type: 'strukturreform',
      period: 'per_ar',
      calculation: 'Övergång från kommunal till statlig skola och nationellt lärarlyft.',
    },
    quote: 'Skolan är klassresans viktigaste verktyg. Alla elever har rätt till studiero och kunskap.',
    source: { url: 'https://utlovat.se/lofte/p-l-01', domain: 'utlovat.se' },
  },
  {
    id: 'p-l-02',
    title: 'Utöka LSS-rätten och rädda personlig assistans för alla med behov',
    slug: 'utoka-lss-personlig-assistans',
    parties: ['l'],
    category: 'välfärd',
    status: 'aktiv',
    cost: {
      msek_base: 3300,
      type: 'utgift',
      period: 'per_ar',
      calculation: 'Förstärkt schablonbelopp och slopade restriktioner för grundläggande behov.',
    },
    quote: 'Frihet och värdighet för personer med funktionsnedsättning är en liberal frihetsfråga.',
    source: { url: 'https://utlovat.se/lofte/p-l-02', domain: 'utlovat.se' },
  },
  {
    id: 'p-l-03',
    title: 'Fler timmar i svenska för nyanlända och obligatorisk språkförskola',
    slug: 'sprakforskola-fler-timmar-svenska',
    parties: ['l'],
    category: 'utbildning',
    status: 'aktiv',
    cost: {
      msek_base: 1900,
      type: 'utgift',
      period: 'per_ar',
      calculation: 'Språktest vid 2,5 år och obligatorisk förskola vid bristande svenska.',
    },
    quote: 'Svenska språket är nyckeln till integration och ett självständigt vuxenliv.',
    source: { url: 'https://utlovat.se/lofte/p-l-03', domain: 'utlovat.se' },
  },
  {
    id: 'p-l-04',
    title: 'Svenskt medlemskap i Euron för stabil valuta och lägre räntor',
    slug: 'svenskt-medlemskap-i-euron',
    parties: ['l'],
    category: 'övrigt',
    status: 'aktiv',
    cost: {
      msek_base: 0,
      type: 'valutareform',
      period: 'engang',
      calculation: 'Förberedelser för folkomröstning och övergång till Euro.',
    },
    quote: 'Sverige ska vara fullvärdig medlem i Europas ekonomiska kärna med stark valuta.',
    source: { url: 'https://utlovat.se/lofte/p-l-04', domain: 'utlovat.se' },
  },

  // Miljöpartiet
  {
    id: 'p-mp-01',
    title: 'Klimatkliv 2.0: 100 miljarder i gröna investeringar för nollutsläpp',
    slug: 'klimatkliv-grona-investeringar-nollutslapp',
    parties: ['mp'],
    category: 'klimat-miljö',
    status: 'aktiv',
    cost: {
      msek_base: 15000,
      type: 'investering',
      period: 'per_ar',
      calculation: 'Stöd till sol- och vindkraft, elektrifiering av transporter och våtmarksåterställning.',
    },
    quote: 'Klimatkrisen kräver historiska investeringar i förnybar energi och framtidens jobb.',
    source: { url: 'https://utlovat.se/lofte/p-mp-01', domain: 'utlovat.se' },
  },
  {
    id: 'p-mp-02',
    title: 'Skydda 30 % av Sveriges skog och hav för biologisk mångfald',
    slug: 'skydda-skog-och-hav-biologisk-mangfald',
    parties: ['mp'],
    category: 'klimat-miljö',
    status: 'aktiv',
    cost: {
      msek_base: 4500,
      type: 'utgift',
      period: 'per_ar',
      calculation: 'Anslag för naturreservat, marina skyddsområden och ersättning till markägare.',
    },
    quote: 'Naturen är vår livförsäkring. Vi måste stoppa massutrotningen av arter.',
    source: { url: 'https://utlovat.se/lofte/p-mp-02', domain: 'utlovat.se' },
  },
  {
    id: 'p-mp-03',
    title: 'Halverat pris på tågresor och utbyggda nattåg till Europa',
    slug: 'halverat-pris-tagresor-nattag',
    parties: ['mp'],
    category: 'infrastruktur',
    status: 'aktiv',
    cost: {
      msek_base: 5000,
      type: 'utgift',
      period: 'per_ar',
      calculation: 'Subventionerat tågresande och upphandlad internationell nattågstrafik.',
    },
    quote: 'Det ska alltid vara billigare och enklare att välja tåget än flyget.',
    source: { url: 'https://utlovat.se/lofte/p-mp-03', domain: 'utlovat.se' },
  },
  {
    id: 'p-mp-04',
    title: 'Stopp för nya fossila subventioner och avgift på engångsplast',
    slug: 'stopp-fossila-subventioner-engangsplast',
    parties: ['mp'],
    category: 'klimat-miljö',
    status: 'aktiv',
    cost: {
      msek_base: -4000, // Minskade subventioner/skatt
      type: 'inkomst',
      period: 'per_ar',
      calculation: 'Avveckling av skatterabatter på fossila bränslen.',
    },
    quote: 'Skattebetalarnas pengar ska inte gå till att elda på klimatkrisen.',
    source: { url: 'https://utlovat.se/lofte/p-mp-04', domain: 'utlovat.se' },
  },
];
